---
title: Weekends
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
paginate: 100
language: en-uk
words_per_minute: 200
baseurl: "/"
description: from Fridei to Sundei
cover: https://i.vgy.me/4iEoYX.jpg
logo: assets/images/blog-icon.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
CNAME: 
navigation: true
subscribers: true
twitter: nhungngaycuoituan
instagram: nhungngaycuoituan
facebook: nhungngaycuoituan
disqus: false
disqus_shortname: jekyller
google_analytics: UA-69281367-1
permalink: "/:title"
plugins_dir:
- _plugins
plugins:
- jekyll-paginate
- jekyll-feed
feed:
  path: feed.xml
safe: false
lsi: false
username: jekyller
repo: jasper2
branch: master
relative_source: "../jasper2/"
destination: "../jasper2-pages/"
production_url: https://jekyller.github.io/jasper2/
source_url: https://github.com/jekyller/jasper2/
exclude:
- assets/css
- node_modules
- vendor
- ".travis.yml"
- Gemfile
- Gemfile.lock
- GHOST.txt
- gulpfile.js
- LICENSE
- package.json
- package-lock.json
- Rakefile
- README.md
- script.py
- changelog.md
- "*.Rmd"
- ".git*"
